var test_error = new Error()

exports.test = function(next, assert) {
    f(true, function(err, result) {
        assert.equal(err, test_error)

        f(false, function(err, result) {
            assert.is_null(err)
            assert.equal(result, 5)
            next()
        })
    })
}

function f_(crash) {
    if (g(crash)) {
        return 5
    }
}

function g(crash) {
    if (crash) {
        throw test_error
    }
    return true
}
