/*** Generated by streamline.js - DO NOT EDIT ***/
var test_error = new Error();
exports.test = function(next, assert) {
    f(true, function(err, result) {
        assert.equal(err, test_error);
        f(false, function(err, result) {
            assert.is_null(err);
            assert.equal(result, 2);
            next();
        });
    });
};
function f(crash, callback) {
    try {
        result4 = (g(crash) + 1);
    } catch (err) {
        if (callback) {
            return callback(err)
        } else {
            throw err
        };
    };
    if (callback) {
        return callback(null, result4)
    };
};
function g(crash) {
    if (crash) {
        throw test_error;
    }
     else {
        return 1;
    }
;
};
