/*** Generated by streamline.js - DO NOT EDIT ***/
var test_error = new Error();
exports.test = function(next, assert) {
    f(true, function(err, result) {
        assert.equal(err, test_error);
        f(false, function(err, result) {
            assert.is_null(err);
            assert.equal(result, 2);
            next();
        });
    });
};
function f(crash, callback) {
    callback = (callback || __throw_1);
    try {
        __retval_2 = (g(crash) + 1);
    } catch (err) {
        return callback(err);
    };
    return callback(null, __retval_2);
};
function g(crash) {
    if (crash) {
        throw test_error;
    }
     else {
        return 1;
    }
;
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
